import os
import oracledb
from dotenv import load_dotenv

load_dotenv()

# Configurações de Conexão com o Oracle
ORACLE_USER = os.getenv("ORACLE_USER")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
ORACLE_DSN = os.getenv("ORACLE_DSN", "localhost:1521/FREEPDB1")


def get_connection():
    return oracledb.connect(
        user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=ORACLE_DSN
    )


def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    def executar_ddl(sql):
        try:
            cursor.execute(sql)
        except oracledb.DatabaseError as e:
            error_obj, = e.args
            # ORA-00955 (objeto existe) ou ORA-01430 (coluna existe)
            if error_obj.code not in (955, 1430):
                raise e

    # 1. Tabela Clientes
    executar_ddl("""
        CREATE TABLE clientes (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR2(100) NOT NULL,
            email VARCHAR2(100),
            telefone VARCHAR2(20)
        )
    """)

    # 2. Tabela Funcionários
    executar_ddl("""
        CREATE TABLE funcionarios (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR2(100) NOT NULL,
            equipe VARCHAR2(50),
            cargo VARCHAR2(50),
            email VARCHAR2(100)
        )
    """)

    # 3. Tabela Chamados
    executar_ddl("""
        CREATE TABLE chamados (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cliente_id NUMBER,
            funcionario_id NUMBER,
            categoria VARCHAR2(50) NOT NULL,
            aplicacao VARCHAR2(100) NOT NULL,
            prioridade VARCHAR2(20) DEFAULT 'Média',
            descricao CLOB,
            solucao CLOB,
            status VARCHAR2(20) DEFAULT 'Aberto',
            data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            data_fechamento TIMESTAMP,
            sla_horas NUMBER DEFAULT 24,
            CONSTRAINT fk_chamado_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
            CONSTRAINT fk_chamado_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id)
        )
    """)

    # Tenta adicionar a coluna 'solucao' caso a tabela 'chamados' já existisse no seu Oracle
    executar_ddl("ALTER TABLE chamados ADD solucao CLOB")

    # 4. Tabela Historico/Anotações dos Chamados (Essencial para análise temporal)
    executar_ddl("""
        CREATE TABLE historico_chamados (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chamado_id NUMBER NOT NULL,
            anotacao CLOB NOT NULL,
            data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_hist_chamado FOREIGN KEY (chamado_id) REFERENCES chamados(id)
        )
    """)

    conn.commit()
    cursor.close()
    conn.close()


def salvar_cliente_db(nome, email, telefone):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT INTO clientes (nome, email, telefone) VALUES (:1, :2, :3)", (nome, email, telefone))
    conn.commit()
    cursor.close()
    conn.close()


def salvar_funcionario_db(nome, equipe, cargo, email):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT INTO funcionarios (nome, equipe, cargo, email) VALUES (:1, :2, :3, :4)", (nome, equipe, cargo, email))
    conn.commit()
    cursor.close()
    conn.close()


def listar_clientes_db():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id, nome FROM clientes ORDER BY nome")
    dados = cursor.fetchall()
    cursor.close()
    conn.close()
    return dados


def listar_funcionarios_db():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id, nome FROM funcionarios ORDER BY nome")
    dados = cursor.fetchall()
    cursor.close()
    conn.close()
    return dados


def salvar_chamado_db(cliente_id, funcionario_id, categoria, aplicacao, prioridade, descricao, sla_horas=24):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO chamados (cliente_id, funcionario_id, categoria, aplicacao, prioridade, descricao, sla_horas)
        VALUES (:1, :2, :3, :4, :5, :6, :7)
    """, (cliente_id, funcionario_id, categoria, aplicacao, prioridade, descricao, sla_horas))
    conn.commit()
    cursor.close()
    conn.close()


def listar_chamados_abertos_db():
    """Retorna os chamados com status 'Aberto' ou 'Em Andamento'."""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT c.id, cl.nome, c.categoria, c.aplicacao, c.prioridade, c.status
        FROM chamados c
        JOIN clientes cl ON c.cliente_id = cl.id
        WHERE c.status != 'Encerrado'
        ORDER BY c.id DESC
    """)
    dados = cursor.fetchall()
    cursor.close()
    conn.close()
    return dados


def adicionar_anotacao_db(chamado_id, anotacao):
    """Registra uma anotação no histórico e altera status para 'Em Andamento' se estivesse 'Aberto'."""
    conn = get_connection()
    cursor = conn.cursor()
    
    cursor.execute("INSERT INTO historico_chamados (chamado_id, anotacao) VALUES (:1, :2)", (chamado_id, anotacao))
    cursor.execute("UPDATE chamados SET status = 'Em Andamento' WHERE id = :1 AND status = 'Aberto'", (chamado_id,))
    
    conn.commit()
    cursor.close()
    conn.close()


def encerrar_chamado_db(chamado_id, solucao):
    """Encerra o chamado e salva a data de fechamento e solução final."""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE chamados 
        SET status = 'Encerrado', 
            solucao = :1, 
            data_fechamento = CURRENT_TIMESTAMP 
        WHERE id = :2
    """, (solucao, chamado_id))
    
    # Registra o encerramento no histórico também
    cursor.execute("INSERT INTO historico_chamados (chamado_id, anotacao) VALUES (:1, :2)", 
                   (chamado_id, f"[CHAMADO ENCERRADO] Solução: {solucao}"))
    
    conn.commit()
    cursor.close()
    conn.close()


def obter_historico_chamado_db(chamado_id):
    """Retorna todo o histórico de anotações de um chamado especifico."""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT TO_CHAR(data_registro, 'DD/MM/YYYY HH24:MI'), anotacao 
        FROM historico_chamados 
        WHERE chamado_id = :1 
        ORDER BY id ASC
    """, (chamado_id,))
    dados = [
        (data_registro, _ler_clob(anotacao))
        for data_registro, anotacao in cursor.fetchall()
    ]
    cursor.close()
    conn.close()
    return dados

def _ler_clob(valor):
    """Converte valores CLOB do Oracle para texto comum."""
    if valor is None:
        return ""
    return valor.read() if hasattr(valor, "read") else str(valor)

def listar_chamados_encerrados_db(
    data_inicio=None,
    data_fim=None,
    cliente_id=None,
    funcionario_id=None
):
    """
    Retorna chamados encerrados com filtros opcionais.
    As datas devem ser informadas no formato YYYY-MM-DD.
    """
    conn = get_connection()
    cursor = conn.cursor()

    sql = """
        SELECT
            c.id,
            cl.nome,
            NVL(f.nome, 'Não atribuído'),
            c.categoria,
            c.aplicacao,
            c.prioridade,
            TO_CHAR(c.data_fechamento, 'DD/MM/YYYY HH24:MI')
        FROM chamados c
        INNER JOIN clientes cl ON cl.id = c.cliente_id
        LEFT JOIN funcionarios f ON f.id = c.funcionario_id
        WHERE c.status = 'Encerrado'
          AND (
                :data_inicio IS NULL
                OR c.data_fechamento >= TO_TIMESTAMP(:data_inicio, 'YYYY-MM-DD')
              )
          AND (
                :data_fim IS NULL
                OR c.data_fechamento < TO_TIMESTAMP(:data_fim, 'YYYY-MM-DD')
                    + INTERVAL '1' DAY
              )
          AND (
                :cliente_id IS NULL
                OR c.cliente_id = :cliente_id
              )
          AND (
                :funcionario_id IS NULL
                OR c.funcionario_id = :funcionario_id
              )
        ORDER BY c.data_fechamento DESC
    """

    parametros = {
        "data_inicio": data_inicio,
        "data_fim": data_fim,
        "cliente_id": cliente_id,
        "funcionario_id": funcionario_id
    }

    cursor.execute(sql, parametros)
    dados = cursor.fetchall()

    cursor.close()
    conn.close()

    return dados

def obter_chamado_encerrado_detalhe_db(chamado_id):
    """Retorna todos os dados necessários para a tela de detalhe de um chamado."""
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT 
            c.id,
            cl.nome AS Cliente,
            NVL(f.nome, 'Nao atribuido') AS tecnico,
            c.categoria,
            c.aplicacao,
            c.prioridade,
            TO_CHAR(c.data_criacao, 'DD/MM/YYYY HH24:MI') AS data_criacao,
            TO_CHAR(c.data_fechamento, 'DD/MM/YYYY HH24:MI') AS data_fechamento,
            c.descricao,
            c.solucao
        FROM chamados c
        JOIN clientes cl ON cl.id = c.cliente_id
        LEFT JOIN funcionarios f ON f.id = c.funcionario_id
        WHERE c.id = :chamado_id 
            AND c.status = 'Encerrado'
    """, {"chamado_id": chamado_id})

    chamado = cursor.fetchone()

    cursor.close()
    conn.close()

    if not chamado:
        return None

    chamado = list(chamado)
    chamado[6] = _ler_clob(chamado[6])  # descricao
    chamado[7] = _ler_clob(chamado[7])  # solucao

    return chamado